# Generated by Django 5.1.1 on 2024-12-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_login', models.TextField(unique=True)),
                ('user_password', models.TextField()),
                ('user_mail', models.TextField(unique=True)),
                ('user_date_new', models.DateTimeField(auto_now_add=True)),
                ('user_date_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='App.user')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
